# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7

jobs:
   test-cases:
          docker:
            - image: cimg/node:16.10
          working_directory: ~/src/
          steps:
            - checkout:
                path: ~/src/
            - run: 
                name: Installing prerequisites
                command: |-
                  node --version
            - run:
                name: Executing test cases
                command: cd src && npm install && npm run unit
              

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  buil-and-test: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test-cases

